replicaCount: 1

webapp:
  name: visr-test
  group: visr-test
  path: /
  tls:
    fqdn: visr-test.k8s.ucar.edu
    secretName: incommon-cert-visr-test
  container: 
    image: docker.io/mattrncar/actix-docker-image:v1
    port: 8080
    memory: 1G
    cpu: 2
